In [23]:
import numpy
import pandas
import matplotlib.pyplot

a = numpy.array([[1,1,1,1], [1,1,1,1], [1,1,1,1], [1,1,1,1]])
print(a)
a.fill(5)
b = a.reshape(2,8)
print(b)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]]
